In [1]:
import numpy as np

In [26]:
a = np.arange(24)

In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
a.ndim

1

b=a.reshape(1,24)

In [56]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
b.ndim

2

In [58]:
e=a.reshape(2,4,3)

In [59]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [48]:
c=np.array([[1,2],[2,3],[3,5]])

In [49]:
c

array([[1, 2],
       [2, 3],
       [3, 5]])

In [50]:
c.shape

(3, 2)

In [51]:
c.shape=(2,3)

In [61]:
c

array([[1, 2, 2],
       [3, 3, 5]])

In [62]:
c.itemsize

4