In [1]:
import numpy as np

In [3]:
a = np.arange(20)

In [4]:
s = slice(2,18,2)
a[s]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [5]:
q = np.arange(2,19)

In [6]:
q

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [7]:
q[2:13:3]

array([ 4,  7, 10, 13])

In [8]:
q[4:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [9]:
q[3:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [10]:
q[0:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
w[:,0][:2]

array([1, 4])

In [12]:
w[1:] #标号从0开始

array([[4, 5, 6],
       [7, 8, 9]])

In [3]:
w[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
w[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
w[...,0]

array([1, 4, 7])

In [15]:
w[0,...]

array([1, 2, 3])

In [16]:
w[...,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [21]:
w[...,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [10]:
w[...,1]

array([2, 5, 8])

In [22]:
w[...,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
w[1,2]

6

In [26]:
w[0,0]

1